namespace Furikiri
{
    static class Const
    {
        public const string LicenseInfo =
            "Generated by Furikiri. Author: Ulysses (wdwxy12345@gmail.com). License: CC BY-NC-SA 4.0";

        public const string RegExp = "RegExp";
        public const string RegExpCompile = "_compile";
    }
}