using System;
// ReSharper disable InconsistentNaming

namespace Furikiri
{
    static class Const
    {
        public const string LicenseInfo =
            "Generated by Furikiri. Author: Ulysses (wdwxy12345@gmail.com). License: CC BY-NC-SA 4.0";

        public const string RegExp = "RegExp";
        public const string RegExpCompile = "_compile";
        public const string Global = "global";
        public const string AnonymousFunctionName = "(anonymous)";
        /// <summary>
        /// A special slot for flag since 0 is (WTF) not represent for it
        /// <para>It shouldn't affect the TJS VM since a normal slot is a short, while this is a int</para>
        /// </summary>
        public const int FlagReg = Int32.MinValue;

        /// <summary>
        /// %0, res, usually void
        /// </summary>
        public const short ResourceReg = 0;
        /// <summary>
        /// %-1, this
        /// </summary>
        public const short ThisReg = -1;
        /// <summary>
        /// %-2, this ?? global
        /// </summary>
        public const short ThisProxyReg = -2;
    }
}