/*
var parseStartTick = System.getTickCount();
dm("スクリプトの読み込みに " + (System.getTickCount() - parseStartTick) + "ms かかりました");

function Test(p1, p2)
{
	var p3 = 3;
	var added = 1 + p3;
	var subed = p3 - 1;
	var muled = p3 * p3;
	var dived = p3 / 2;
	var dived2 = p3 \ 2;
	var eq1 = p3 != 3;
	var eq2 = p3 === added;	
	var b = true;
	var b2 = !b;
	var b3 = b2 || b;
	var p4 = p3 >> 1;
	System.getArgument('aaa','bbb','ccc');
}
*/

function TestLoop(p3)
{
	while(p3 < 0)
	{
	   p3++;
	}
	
	do
	{
	   p3++;
	}
	while(p3 < 10);
	
	for(var i = 0; i < 10; i+=2)
	{
		i++;
	}
	
	if(p3 > 4396)
	{
		p3+=1;
	}
	else
	{
		p3-=1;
	}
	p3 = -p3;
	
	return p3;
}

function TestLoop2(p4)
{
   while (p4 < 0)
   {
		if (p4 > -2)
		{
			p4 +=1;
		}
		else if(p4 > -3)
		{
			p4 +=2;
		}
		else
		{
			p4 +=3;
		}
   }
   return;
}

function TestIf(p5)
{
	if(p5 == 1 || p5 == 2 || p5 == 3)
	{
		p5++;
	}
	
	if(p5 == 4 && p5 == 5 && p5 == 6)
	{
		p5--;
	}
	
	if(p5 == 7 || p5 == 8 && p5 == 9)
	{
		p5 = p5 +2;
	}
}

function TestRegExp()
{
	var r1 = /[0-9]-[0-9]-[0-9]/;
    var r2 = /^;\s*(.*?)\s*=(.*)$/;
    var r3 = /start(.*?)end/gi;
	var r4 = /\\.\\.\\./l;
}

function TestTry()
{
	try
	{
		var n = 1 / 0.0;
		return n;
	}
	catch(e)
	{
		System.inform(e.message);
	}
	System.inform("exit try");
}